// Code generated by "stringer -type=tokenKind"; DO NOT EDIT.

package nets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokTR-0]
	_ = x[tokEOF-1]
	_ = x[tokPL-2]
	_ = x[tokNET-3]
	_ = x[tokARROW-4]
	_ = x[tokIDENT-5]
	_ = x[tokTIMINGC-6]
	_ = x[tokINHIBITOR-7]
	_ = x[tokREAD-8]
	_ = x[tokLABEL-9]
	_ = x[tokILLEGAL-10]
	_ = x[tokMARKING-11]
	_ = x[tokPRIO-12]
	_ = x[tokGT-13]
	_ = x[tokLT-14]
	_ = x[tokSTAR-15]
	_ = x[tokINT-16]
	_ = x[tokNOTE-17]
}

const _tokenKind_name = "tokTRtokEOFtokPLtokNETtokARROWtokIDENTtokTIMINGCtokINHIBITORtokREADtokLABELtokILLEGALtokMARKINGtokPRIOtokGTtokLTtokSTARtokINTtokNOTE"

var _tokenKind_index = [...]uint8{0, 5, 11, 16, 22, 30, 38, 48, 60, 67, 75, 85, 95, 102, 107, 112, 119, 125, 132}

func (i tokenKind) String() string {
	if i < 0 || i >= tokenKind(len(_tokenKind_index)-1) {
		return "tokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenKind_name[_tokenKind_index[i]:_tokenKind_index[i+1]]
}
